leftnav:
- identifier: bbc7600c-0de3-4980-8e78-2e537ddd687e
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: df733917-1aa0-4cda-96e8-dd68213c1daa
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: ed784e72-fee7-48d9-bcee-f40b88619fd9
  name: Class Summaries
  url: /pages/class-summaries
  weight: 30
- identifier: def28f59-bf40-4be3-b34d-3343aaf9ffef
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: external--763591547-1675869452137
  name: 'MIT Library Guide: Comedy'
  url: https://libguides.mit.edu/comedy/home
  weight: 50
- identifier: 8d97e2c4-96fa-44ea-a0bf-2e0bb3d5490e
  name: Essays
  parent: def28f59-bf40-4be3-b34d-3343aaf9ffef
  url: /pages/assignment
  weight: 10
- identifier: 1c1acc28-ea54-4c00-bc95-f31422e3c20a
  name: Report
  parent: def28f59-bf40-4be3-b34d-3343aaf9ffef
  url: /pages/report-guidelines
  weight: 20
- identifier: cb0f4dea-60b6-4c83-93a8-6c4d34389f5d
  name: Discussion Prompts
  parent: def28f59-bf40-4be3-b34d-3343aaf9ffef
  url: /pages/discussion-prompts
  weight: 30
